### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by Remonell** [thethiny/RageQuit-RL#2]
When I am in the main menu doing nothing. Alt + F4 does not do anything with this plugin installed and activated.

**Comment by thethiny** [comment]
Can you check the logs when you press Alt F4? I still use it daily and it works. However you need to use the re-uploaded version (drawn with bad artstyle).

**Comment by Remonell** [comment]
I found the reason for this issue. I installed the plugin and it was disabled by default in the plugin manager. Never happened before with any other plugin.

Why did you reupload the plugin? Whats wrong with this version of it?

**Comment by ridhwan-saal** [comment]
I hard-coded my username in this by accident

**Comment by Remonell** [comment]
I just read that the other upload is verified. Ok got it.

**Comment by thethiny** [comment]
> I just read that the other upload is verified. Ok got it.

That, and this version has my username hard-coded by accident. It only affects build, not using.

**Comment by Remonell** [comment]
> > I just read that the other upload is verified. Ok got it.
> 
> That, and this version has my username hard-coded by accident. It only affects build, not using.

Ahh I see. I installed the reuploaded version and this time it was activated by default.
